### ISSUE TITLE
How do I fix 'ImportError: cannot import name op'?

### ISSUE THREAD

**Issue by utayao** [untom/binet#2]
I have a Ubuntu 14.10 system and have installed binet required dependencies. When I run your sample code and I face such error. How can I fix this problem? Thank you so much.

**Comment by untom** [comment]
what code did you try to run?  What does

    import binet
    print(binet.__file__)


give?

**Comment by codemarsyu** [comment]
Hi, 

I also have a problem when I try to compile the library, I use

> python setup.py build_ext --inplace

It got error message like "/usr/bin/ld: cannot find -lblas","collect2: error: ld returned 1 exit status". It happened after second gcc:

> gcc -pthread -shared -L/home/ruoyu/anaconda2/lib -Wl,-rpath=/home/ruoyu/anaconda2/lib,--no-as-needed build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/binet._external.o -L/home/ruoyu/anaconda2/lib -lgsl -lblas -lpython2.7 -o /home/ruoyu/PycharmProjects/deeptox/binet-master/binet/_external.so

It seems that the the libblas.so is not found in path, but it is in /usr/lib and I have export it to LD_LIBRARY_PATH .  So I did not why this linking failed. I did not change anything in the setup.py.

**Comment by codemarsyu** [comment]
Hi, 

I have the same problem, and I try above two lines

> import binet

> print(binet.__file__)

It outputs:

/home/ruoyu/PycharmProjects/deeptox/binet-master/binet/__init__.py:2: UserWarning: CUDA libraries are not available.
  from binet import op
Traceback (most recent call last):
  File "/home/ruoyu/PycharmProjects/deeptox/binet-master/test_import.py", line 1, in <module>
    from binet.util import train
  File "/home/ruoyu/PycharmProjects/deeptox/binet-master/binet/__init__.py", line 10, in <module>
    __version__ = __pkg_resources.require('binet')[0].version
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 943, in require
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 830, in resolve
    
pkg_resources.DistributionNotFound: The 'binet' distribution was not found and is required by the application

**Comment by untom** [comment]
How did you install binet itself? Did you use pip or setuptools?

**Comment by yvdriess** [comment]
I stumbled on the same issue, installing binet using setuptools. It is probably related to the following warning during setuptool install:
`    missing cimport in module 'binet': binet/op.pyx`

**Comment by untom** [comment]
Could you once more using pip (`pip installieren $path-to-binet`)?

Also, is this using python2 or 3?

**Comment by yvdriess** [comment]
pip successfully runs the installation, but trying to import binet then results in:
`  File "/home/yvandrie/excape/code/wp1/pipeline/binet-master/binet/__init__.py", line 2, in <module>
    from binet import op`

**Comment by untom** [comment]
We usually use python3, and only very sporadically test on py2. But the error definitely sounds like there was an issue with compiling op.pyx using cython. Could you try running cython manually?

**Comment by yvdriess** [comment]
I switched to the intelpython35 distribution, no change to the error in question.

I also still get the cimport warning when running the setuptools install. Note that pip install succeeds without any error/warning.
```
$ python setup.py install
missing cimport in module 'binet': binet/op.pyx
Compiling binet/op.pyx because it changed.
[1/1] Cythonizing binet/op.pyx
...
```

Running cython manually succeeds without any warnings or error messages (-v -Werror flags).

**Comment by yvdriess** [comment]
However, when setuptools compiles the object file for op.c, it does complain (warn only) about deprecated numpy API. The .o is produced normally.

```
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -fstack-protector -O3 -fpic -fPIC -fPIC -DSCIPY_MKL_H -DHAVE_CBLAS -I/home/yvandrie/intel/intelpython35/lib/python3.5/site-packages/numpy/core/include -I/home/yvandrie/intel/intelpython35/include -I/home/yvandrie/intel/intelpython35/include/python3.5m -c binet/op.c -o build/temp.linux-x86_64-3.5/binet/op.o -Wno-unused-function
In file included from /home/yvandrie/intel/intelpython35/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                 from /home/yvandrie/intel/intelpython35/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/yvandrie/intel/intelpython35/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from binet/op.c:301:
/home/yvandrie/intel/intelpython35/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2:                                                   warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"                                                   [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
```

**Comment by untom** [comment]
The warning about the deprecated API is normal and should not produce any mistakes.

So if I understand this correctly, both setuptools and pip do successfully call cython and produce the op.o file, but then still fail to import the `binet.op` submodule. 

Do they also produce the .so file? (after cython, the directory should contain an so file named something along the lines of `op.cpython-35m-x86_64-linux-gnu.so`)?

**Comment by yvdriess** [comment]
Yes, I found it in:
build/lib.linux-x86_64-3.5/binet/_external.cpython-35m-x86_64-linux-gnu.so
build/lib.linux-x86_64-3.5/binet/op.cpython-35m-x86_64-linux-gnu.so

**Comment by untom** [comment]
Just to make sure:  you're unable to run  `from binet import op`, while `import binet` does work?

**Comment by yvdriess** [comment]
Both fail with the same error:
```
  File "/home/yvandrie/excape/code/wp1/pipeline/binet-master/binet/__init__.py", line 2, in <module>
    from binet import op
ImportError: cannot import name 'op'
```

Running __init__.py manually revealed some CUDA issues. These are now fixed, I can run `binet/__init__.py` but the given error persists.

**Comment by yvdriess** [comment]
I had a colleague try the installation on a similar machine (Ubuntu, but different python distribution), which showed the same cimport missing error message.

**Comment by yvdriess** [comment]
I found the problem by looking at the strace output. As usual it was really stupid: python found a `binet/` directory first, before finding the `.egg`

Running python in a complete different working directory and taking care that the `.py` file is not in a directory containing a binet/ directory fixes the above `op` import issue.
